/*
 * Приложение для робота-пылесоса
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Error
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-22T15:17:37.018Z[GMT]")
public class Error {
  @SerializedName("code_error")
  private Integer codeError = null;

  @SerializedName("message_error")
  private String messageError = null;

  public Error codeError(Integer codeError) {
    this.codeError = codeError;
    return this;
  }

   /**
   * Get codeError
   * @return codeError
  **/
  @Schema(required = true, description = "")
  public Integer getCodeError() {
    return codeError;
  }

  public void setCodeError(Integer codeError) {
    this.codeError = codeError;
  }

  public Error messageError(String messageError) {
    this.messageError = messageError;
    return this;
  }

   /**
   * Get messageError
   * @return messageError
  **/
  @Schema(required = true, description = "")
  public String getMessageError() {
    return messageError;
  }

  public void setMessageError(String messageError) {
    this.messageError = messageError;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.codeError, error.codeError) &&
        Objects.equals(this.messageError, error.messageError);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeError, messageError);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    codeError: ").append(toIndentedString(codeError)).append("\n");
    sb.append("    messageError: ").append(toIndentedString(messageError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
