/*
 * Приложение для робота-пылесоса
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Robot
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-22T15:17:37.018Z[GMT]")
public class Robot {
  @SerializedName("ID_robot")
  private Integer idRobot = null;

  @SerializedName("Name_machine")
  private String nameMachine = null;

  @SerializedName("Model")
  private String model = null;

  @SerializedName("Version")
  private Integer version = null;

  @SerializedName("Capacity_battery")
  private Integer capacityBattery = null;

  @SerializedName("IP-adress")
  private Integer ipAdress = null;

  @SerializedName("User_id")
  private Integer userId = null;

  public Robot idRobot(Integer idRobot) {
    this.idRobot = idRobot;
    return this;
  }

   /**
   * Get idRobot
   * @return idRobot
  **/
  @Schema(example = "382292", required = true, description = "")
  public Integer getIdRobot() {
    return idRobot;
  }

  public void setIdRobot(Integer idRobot) {
    this.idRobot = idRobot;
  }

  public Robot nameMachine(String nameMachine) {
    this.nameMachine = nameMachine;
    return this;
  }

   /**
   * Имя, присвоенное роботу
   * @return nameMachine
  **/
  @Schema(example = "Benedikt", required = true, description = "Имя, присвоенное роботу")
  public String getNameMachine() {
    return nameMachine;
  }

  public void setNameMachine(String nameMachine) {
    this.nameMachine = nameMachine;
  }

  public Robot model(String model) {
    this.model = model;
    return this;
  }

   /**
   * Название модели робота
   * @return model
  **/
  @Schema(example = "Garlyn", required = true, description = "Название модели робота")
  public String getModel() {
    return model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public Robot version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Версия ПО
   * @return version
  **/
  @Schema(required = true, description = "Версия ПО")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public Robot capacityBattery(Integer capacityBattery) {
    this.capacityBattery = capacityBattery;
    return this;
  }

   /**
   * Емкость батареи
   * @return capacityBattery
  **/
  @Schema(example = "1900", required = true, description = "Емкость батареи")
  public Integer getCapacityBattery() {
    return capacityBattery;
  }

  public void setCapacityBattery(Integer capacityBattery) {
    this.capacityBattery = capacityBattery;
  }

  public Robot ipAdress(Integer ipAdress) {
    this.ipAdress = ipAdress;
    return this;
  }

   /**
   * Get ipAdress
   * @return ipAdress
  **/
  @Schema(required = true, description = "")
  public Integer getIpAdress() {
    return ipAdress;
  }

  public void setIpAdress(Integer ipAdress) {
    this.ipAdress = ipAdress;
  }

  public Robot userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(example = "382292", required = true, description = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Robot robot = (Robot) o;
    return Objects.equals(this.idRobot, robot.idRobot) &&
        Objects.equals(this.nameMachine, robot.nameMachine) &&
        Objects.equals(this.model, robot.model) &&
        Objects.equals(this.version, robot.version) &&
        Objects.equals(this.capacityBattery, robot.capacityBattery) &&
        Objects.equals(this.ipAdress, robot.ipAdress) &&
        Objects.equals(this.userId, robot.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(idRobot, nameMachine, model, version, capacityBattery, ipAdress, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Robot {\n");
    
    sb.append("    idRobot: ").append(toIndentedString(idRobot)).append("\n");
    sb.append("    nameMachine: ").append(toIndentedString(nameMachine)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    capacityBattery: ").append(toIndentedString(capacityBattery)).append("\n");
    sb.append("    ipAdress: ").append(toIndentedString(ipAdress)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
